STANDARD_RENDER_PRESETS = [
    "H.264 Master",
    "HyperDeck",
    "H.265 Master",
    "ProRes 422 HQ",
    "YouTube - 720p",
    "YouTube - 1080p",
    "YouTube - 1440p",
    "YouTube - 2160p",
    'Vimeo - 720p', 
    'Vimeo - 1080p', 
    'Vimeo - 2160p', 
    'Twitter - 720p', 
    'Twitter - 1080p', 
    'Blackmagic Cloud', 
    'Dropbox - 720p', 
    'Dropbox - 1080p', 
    'Dropbox - 2160p', 
    'Replay - 720p', 
    'Replay - 1080p', 
    'Replay - 2160p', 
    'Frame.io', 
    'IMF - Generic', 
    'IMF - 20th Century Fox', 
    'IMF - Netflix', 
    'IMF - Sony Pictures', 
    'FCP - Final Cut Pro 7', 
    'FCP - Final Cut Pro X', 
    'Premiere XML', 
    'Audio Only', 
    'AVID AAF', 
    'Pro Tools', 
]